Prestart  nguyenxuanthang
STU-React-Team/excersise-prestart-week pull request #11
Opened 2019-12-17 09:23 UTC by thangnguyen1111

Viết nội dung Training trong file README.md

2019-12-17 09:32 UTC, thinhphamstd requested changes
Em thay đổi ngay để a merge nhé

2019-12-17 09:32 UTC, thinhphamstd commented on .idea/encodings.xml
> +<?xml version="1.0" encoding="UTF-8"?>
ignore folder .idea đi

2019-12-17 09:32 UTC, thinhphamstd commented on .idea/excersise-prestart-week.iml
> +<?xml version="1.0" encoding="UTF-8"?>
^^^

2019-12-17 09:32 UTC, thinhphamstd commented on .idea/excersise-prestart-week.iml
> +<module type="WEB_MODULE" version="4">
^^^

2019-12-17 09:32 UTC, thinhphamstd commented on .idea/misc.xml
> +<?xml version="1.0" encoding="UTF-8"?>
^^^

2019-12-17 09:32 UTC, thinhphamstd commented on .idea/misc.xml
> +  <component name="JavaScriptSettings">
^^^

2019-12-17 09:32 UTC, thinhphamstd commented on .idea/modules.xml
> +<project version="4">
^^^

2019-12-17 09:32 UTC, thinhphamstd commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
^^^

2019-12-17 09:32 UTC, thinhphamstd commented on .idea/workspace.xml
> +<project version="4">
^^^

2019-12-17 09:32 UTC, thinhphamstd commented on README.md
> +    - Bài tập 4 (nhóm): Kết hợp tất cả kiến thức đã có vào project [theo yêu cầu của mentor]
- Chỉ cần nêu nội dung cho bài tập 1 thôi.
- những bài tập 2-4 sẽ được ghi trong repo riêng
- Có thể chuyển những thứ này qua readme ở repo intership-dicussion

2019-12-17 09:32 UTC, thinhphamstd commented on README.md
> +    4 - Reducer
Chỉ ghi những kiến thức cần thiết cho bài tập này thôi

2019-12-17 09:49 UTC, thangnguyen1111 commented on .idea/encodings.xml
> +<?xml version="1.0" encoding="UTF-8"?>
ok a

2019-12-17 10:26 UTC, thinhphamstd requested changes
dùng git rm [tenfile]

2019-12-17 10:26 UTC, thinhphamstd commented on .idea/encodings.xml
> +<?xml version="1.0" encoding="UTF-8"?>
- Anh đoán là e git add . trước khi viết vào ignore
- bây giờ em phải dùng git rm [tenfile] để remove hết nó ra từ cái commit của em thì mới được

2019-12-17 14:38 UTC, thangnguyen1111 commented
đã delete thư mục .idea và sửa lại nội dung file README.md

2019-12-18 02:54 UTC, thinhphamstd approved these changes
good job

2019-12-18 02:54 UTC, merged